export const APP_CATALOG = [
  {
    id: 'launcher',
    name: 'SurveyFoundry',
    description: 'Projects, evidence, and outputs—end to end.',
    entryHtml: 'index.html',
    iconPath: '/assets/icons/SurveyFoundry.png',
    color: '#355C7D',
    accent: '#F8B195',
    glyph: 'SC',
  },
  {
    id: 'ros-lookup',
    name: 'RecordQuarry',
    description: 'Harvests plats, ROS, CP&F, parcels, and subdivisions into structured evidence.',
    entryHtml: 'RecordQuarry.html',
    iconPath: '/assets/icons/RecordQuarry.png',
    color: '#2A9D8F',
    accent: '#E9F5DB',
    glyph: 'ROS',
  },
  {
    id: 'pointforge-transformer',
    name: 'PointForge',
    description: 'Builds the canonical point set (coords + provenance + weights).',
    entryHtml: 'POINT_TRANSFORMER.HTML',
    iconPath: '/assets/icons/PointForge.png',
    color: '#3A5A40',
    accent: '#D8F3DC',
    glyph: 'PT',
  },
  {
    id: 'viewport-sketch',
    name: 'LineSmith',
    description: 'Turns points into boundaries, alignments, and structure.',
    entryHtml: 'VIEWPORT.HTML',
    iconPath: '/assets/icons/LineSmith.png',
    color: '#0D3B66',
    accent: '#FAF0CA',
    glyph: 'PB',
  },
  {
    id: 'cpnf-corners',
    name: 'PLSS + CP&F Explorer',
    description: 'Map tool for PLSS aliquots, corner geometry labels, and nearby Ada County CP&F records.',
    entryHtml: 'CPNF.HTML',
    iconPath: '/assets/icons/cpnf-corners.svg',
    color: '#BC4749',
    accent: '#FFE8D6',
    glyph: 'CP',
  },
  {
    id: 'project-browser',
    name: 'Project Browser',
    description: 'Browse the symbolic project-file folder structure as a standalone app.',
    entryHtml: 'PROJECT_BROWSER.html',
    iconPath: '/assets/icons/project-browser.svg',
    color: '#64748B',
    accent: '#E2E8F0',
    glyph: 'PB',
  },
  {
    id: 'ros-ocr',
    name: 'ROS Basis Extractor',
    description: 'Upload a Record of Survey PDF and extract ranked basis-of-bearing candidates using OCR.',
    entryHtml: 'ROS_OCR.html',
    iconPath: '/assets/icons/ros-ocr.svg',
    color: '#6A4C93',
    accent: '#F2E9FF',
    glyph: 'OCR',
  },
];

export function listApps() {
  return APP_CATALOG.map(({ color, accent, glyph, ...publicApp }) => publicApp);
}
