export const APP_CATALOG = [
  {
    id: 'launcher',
    name: 'SurveyFoundry',
    description: 'Projects, evidence, and outputs—end to end.',
    entryHtml: 'index.html',
    iconPath: '/assets/icons/SurveyFoundry.png',
    color: '#355C7D',
    accent: '#F8B195',
    glyph: 'SC',
  },
  {
    id: 'ros-lookup',
    name: 'RecordQuarry',
    description: 'Harvests plats, ROS, CP&F, parcels, and subdivisions into structured evidence.',
    entryHtml: 'RecordQuarry.html',
    iconPath: '/assets/icons/RecordQuarry.png',
    color: '#2A9D8F',
    accent: '#E9F5DB',
    glyph: 'ROS',
  },
  {
    id: 'pointforge-transformer',
    name: 'PointForge',
    description: 'Builds the canonical point set (coords + provenance + weights).',
    entryHtml: 'POINT_TRANSFORMER.HTML',
    iconPath: '/assets/icons/PointForge.png',
    color: '#3A5A40',
    accent: '#D8F3DC',
    glyph: 'PT',
  },
  {
    id: 'viewport-sketch',
    name: 'LineSmith',
    description: 'Turns points into boundaries, alignments, and structure.',
    entryHtml: 'VIEWPORT.HTML',
    iconPath: '/assets/icons/LineSmith.png',
    color: '#0D3B66',
    accent: '#FAF0CA',
    glyph: 'PB',
  },
  {
    id: 'project-browser',
    name: 'EvidenceDesk',
    description: 'Browse the symbolic project-file folder structure as a standalone app.',
    entryHtml: 'PROJECT_BROWSER.html',
    iconPath: '/assets/icons/EvidenceDesk.png',
    color: '#64748B',
    accent: '#E2E8F0',
    glyph: 'PB',
  },
  {
    id: 'utilities-pack',
    name: 'UtilitiesPack',
    description: 'Fetches utility records, keeps state-plane coordinates, and exports power utility CSV bundles.',
    entryHtml: 'UtilitiesPack.html',
    iconPath: '/assets/icons/UtilitiesPack.png',
    color: '#1D4ED8',
    accent: '#DBEAFE',
    glyph: 'UP',
  },
  {
    id: 'equipment-log',
    name: 'EquipmentLog',
    description: 'Record equipment setup logs: rodman, height, reference point, setup time, and job file.',
    entryHtml: 'EquipmentLog.html',
    iconPath: '/assets/icons/EquipmentLog.svg',
    color: '#7C3AED',
    accent: '#EDE9FE',
    glyph: 'EL',
  },
  {
    id: 'crew-manager',
    name: 'CrewManager',
    description: 'Manage field crew team member profiles, job titles, contact info, and roles.',
    entryHtml: 'CrewManager.html',
    iconPath: '/assets/icons/CrewManager.svg',
    color: '#0F4C75',
    accent: '#BFDBFE',
    glyph: 'CM',
  },
  {
    id: 'arrowhead-ar',
    name: 'ArrowHead',
    description: 'Mobile AR viewer that overlays LineSmith points and linework on the live camera feed.',
    entryHtml: 'ArrowHead.html',
    iconPath: '/assets/icons/Arrowhead.png',
    color: '#0F766E',
    accent: '#CCFBF1',
    glyph: 'AR',
    experimental: true,
  },

  {
    id: 'boundary-lab',
    name: 'BoundaryLab',
    description: 'Traverse closure lab with ordered bearings/distances, live boundary preview, and misclosure metrics.',
    entryHtml: 'BoundaryLab.html',
    iconPath: '/assets/icons/BoundaryLab.png',
    color: '#0F766E',
    accent: '#BFDBFE',
    glyph: 'BL',
    experimental: true,
  },

  // {
  //   id: 'cpnf-corners',
  //   name: 'PLSS + CP&F Explorer',
  //   description: 'Map tool for PLSS aliquots, corner geometry labels, and nearby Ada County CP&F records.',
  //   entryHtml: 'CPNF.HTML',
  //   iconPath: '/assets/icons/cpnf-corners.svg',
  //   color: '#BC4749',
  //   accent: '#FFE8D6',
  //   glyph: 'CP',
  //   experimental: true,
  // },
  // {
  //   id: 'ros-ocr',
  //   name: 'ROS Basis Extractor',
  //   description: 'Upload a Record of Survey PDF and extract ranked basis-of-bearing candidates using OCR.',
  //   entryHtml: 'ROS_OCR.html',
  //   iconPath: '/assets/icons/ros-ocr.svg',
  //   color: '#6A4C93',
  //   accent: '#F2E9FF',
  //   glyph: 'OCR',
  //   experimental: true,
  // },
];

export function listApps() {
  return APP_CATALOG.map(({ color, accent, glyph, ...publicApp }) => publicApp);
}
