export const APP_CATALOG = [
  {
    id: 'launcher',
    name: 'SurveyFoundry',
    description: 'Central launchpad that links all SurveyFoundry tools from one start page.',
    entryHtml: 'index.html',
    iconPath: '/assets/icons/launcher.svg',
    color: '#355C7D',
    accent: '#F8B195',
    glyph: 'SC',
  },
  {
    id: 'ros-lookup',
    name: 'RecordQuarry',
    description: 'Address-first lookup app for parcels, sections, ROS records, aliquots, and proxied PDF links.',
    entryHtml: 'RecordQuarry.html',
    iconPath: '/assets/icons/ros-lookup.svg',
    color: '#2A9D8F',
    accent: '#E9F5DB',
    glyph: 'ROS',
  },
  {
    id: 'cpnf-corners',
    name: 'PLSS + CP&F Explorer',
    description: 'Map tool for PLSS aliquots, corner geometry labels, and nearby Ada County CP&F records.',
    entryHtml: 'CPNF.HTML',
    iconPath: '/assets/icons/cpnf-corners.svg',
    color: '#BC4749',
    accent: '#FFE8D6',
    glyph: 'CP',
  },
  {
    id: 'ros-ocr',
    name: 'ROS Basis Extractor',
    description: 'Upload a Record of Survey PDF and extract ranked basis-of-bearing candidates using OCR.',
    entryHtml: 'ROS_OCR.html',
    iconPath: '/assets/icons/ros-ocr.svg',
    color: '#6A4C93',
    accent: '#F2E9FF',
    glyph: 'OCR',
  },
  {
    id: 'pointforge-transformer',
    name: 'PointForge Transformer',
    description: 'Coordinate transformer and renumbering helper for NAD83 Idaho West point data workflows.',
    entryHtml: 'POINT_TRANSFORMER.HTML',
    iconPath: '/assets/icons/pointforge-transformer.svg',
    color: '#3A5A40',
    accent: '#D8F3DC',
    glyph: 'PT',
  },
  {
    id: 'viewport-sketch',
    name: 'LineSmith',
    description: 'Interactive drafting workspace for points, bearings, and geometry construction workflows.',
    entryHtml: 'VIEWPORT.HTML',
    iconPath: '/assets/icons/viewport-sketch.svg',
    color: '#0D3B66',
    accent: '#FAF0CA',
    glyph: 'PB',
  },
];

export function listApps() {
  return APP_CATALOG.map(({ color, accent, glyph, ...publicApp }) => publicApp);
}
